/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JProgressBar;
import javax.swing.Timer;
import javax.swing.plaf.ProgressBarUI;

/**
 *
 * @author andre
 */
public class PantallaULP extends javax.swing.JFrame {

    private int pulsos = 10;
    private String activado="Activado!";
    private boolean camaraOn=false, microfonoOn=false, screenOn=false;
    private boolean aprenderClases, aprenderRelaciones, aprenderHerencia, aprenderColecciones, eventooosRandom;
    private String[] directivos = {"Dir. Carlos Palloti", "Profe Hugo", "Coach Andrea Muñoz", ""};
    private String[] eventosBien={"Coach Seba resuelve las dudas del equipo.","Coach Andrea admite tu reingreso a la sala.","El Director Carlos levanta el animo de la jornada.","Tu equipo resuelve los extras de una.","Aprobaste el check.","Coach Seba resuelve las dudas del equipo.","Coach Andrea admite tu reingreso a la sala.","La musiquita de Seba es una caricia a la mente.","El Coach Eze ayudó al equipo a destrabarse.","Aprendiste muchos conceptos hoy."};
    private String[] eventosMal={"Ninguno de tus compañeros enciende la cámara.","Llegaste tarde a 3 encuentros seguidos.","Nueva Guia. Mucho material para leer.","Tu equipo está ausente.","Desaprobaste el check.","Se cerró zoom inesperadamente.","Llegaste tarde a 3 encuentros seguidos.","Nueva Guia. Mucho material para leer.","Hay que rehacer todos los ejercicios porque estaban mal planteados.","Desaprobaste el check."};

    /**
     * Creates new form PantallaULP
     */
    public PantallaULP() {
        initComponents();
        //JProgressBar progresoBar = new JProgressBar();
        //progresoBar.setValue(0);
        Timer timerGral = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                totalPulsos.setText(Integer.toString(pulsos));
                System.out.println("Esto es del general");
                progresoBar.setValue(pulsos * 100 / 10000);

                if (pulsos >= 100 && aprenderClases == false) {
                    comprarAClasess.setEnabled(true);

                } else {
                    comprarAClasess.setEnabled(false);
                }
                if (pulsos >= 200 && aprenderRelaciones == false) {
                    comprarARelaciones.setEnabled(true);
                } else {
                    comprarARelaciones.setEnabled(false);
                }
                
                if (pulsos >= 400 && aprenderHerencia == false) {
                    comprarAHerencia.setEnabled(true);
                } else {
                    comprarAHerencia.setEnabled(false);
                }
                if (pulsos >= 600 && aprenderColecciones == false) {
                    comprarAColecciones.setEnabled(true);
                } else {
                    comprarAColecciones.setEnabled(false);
                }
                if (pulsos >= 50 && eventooosRandom == false) {
                    comprarEventosR.setEnabled(true);
                } else {
                    comprarEventosR.setEnabled(false);
                }
                
                if(pulsos >= 1000){
                    if(!camaraOn){
                        prenderCamara1.setEnabled(true);
                    }
                    if(!microfonoOn){
                        prenderMic.setEnabled(true);
                    }
                    if(!camaraOn){
                        compartirPanta.setEnabled(true);
                    }
                    
                }

            }

        });
        timerGral.setRepeats(true);
        timerGral.setCoalesce(true);
        timerGral.start();

        Timer timer = new Timer(2000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                pulsos++;

            }

        });
        timer.setRepeats(true);
        timer.setCoalesce(true);
        timer.start();

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pPrincipal = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        progresoBar = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        eventosRPulsos = new javax.swing.JLabel();
        eventosRandomLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        salaLabel = new javax.swing.JLabel();
        numSalaLabel = new javax.swing.JLabel();
        pLateral = new javax.swing.JPanel();
        totalPulsos = new javax.swing.JLabel();
        pulsosTexto = new javax.swing.JLabel();
        comprarAClasess = new javax.swing.JButton();
        costoAClases = new javax.swing.JLabel();
        comprarARelaciones = new javax.swing.JButton();
        costoARelaciones = new javax.swing.JLabel();
        comprarAHerencia = new javax.swing.JButton();
        costoAHerencia = new javax.swing.JLabel();
        comprarAColecciones = new javax.swing.JButton();
        costoAColecciones = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cheatInput = new javax.swing.JPasswordField();
        okCheat = new javax.swing.JButton();
        comprarEventosR = new javax.swing.JButton();
        costoEventosR = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        prenderMic = new javax.swing.JButton();
        prenderCamara1 = new javax.swing.JButton();
        compartirPanta = new javax.swing.JButton();
        costoMic = new javax.swing.JLabel();
        costoCamara1 = new javax.swing.JLabel();
        costoPantalla1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("The Pulsos Game: ULP Edition");

        pPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/eggcooplogo.png"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        progresoBar.setForeground(new java.awt.Color(255, 204, 0));
        progresoBar.setToolTipText("Barra de progreso");
        progresoBar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                progresoBarStateChanged(evt);
            }
        });

        jLabel2.setText("Eventos random");

        eventosRPulsos.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        eventosRPulsos.setForeground(new java.awt.Color(102, 102, 102));
        eventosRPulsos.setText("+/-0");

        eventosRandomLabel.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        eventosRandomLabel.setForeground(new java.awt.Color(102, 102, 102));
        eventosRandomLabel.setText("Sin Eventos");

        salaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salaLabel.setText("Sala:");
        salaLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        numSalaLabel.setFont(new java.awt.Font("Poppins ExtraBold", 0, 12)); // NOI18N
        numSalaLabel.setForeground(new java.awt.Color(102, 102, 102));
        numSalaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numSalaLabel.setText("00");
        numSalaLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pPrincipalLayout = new javax.swing.GroupLayout(pPrincipal);
        pPrincipal.setLayout(pPrincipalLayout);
        pPrincipalLayout.setHorizontalGroup(
            pPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPrincipalLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(589, 589, 589))
                    .addGroup(pPrincipalLayout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(pPrincipalLayout.createSequentialGroup()
                        .addComponent(eventosRandomLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(eventosRPulsos)
                        .addGap(17, 17, 17))))
            .addGroup(pPrincipalLayout.createSequentialGroup()
                .addGroup(pPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pPrincipalLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(pPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(progresoBar, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pPrincipalLayout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(jButton1))))
                    .addGroup(pPrincipalLayout.createSequentialGroup()
                        .addGap(303, 303, 303)
                        .addComponent(salaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numSalaLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pPrincipalLayout.setVerticalGroup(
            pPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPrincipalLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salaLabel)
                    .addComponent(numSalaLabel))
                .addGap(41, 41, 41)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(progresoBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(277, 277, 277)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eventosRandomLabel)
                    .addComponent(eventosRPulsos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pLateral.setBackground(new java.awt.Color(248, 248, 248));

        totalPulsos.setBackground(new java.awt.Color(248, 248, 248));
        totalPulsos.setFont(new java.awt.Font("Poppins", 1, 48)); // NOI18N
        totalPulsos.setForeground(new java.awt.Color(51, 51, 51));
        totalPulsos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalPulsos.setLabelFor(pulsosTexto);
        totalPulsos.setText("10");
        totalPulsos.setToolTipText("Pulsos");

        pulsosTexto.setBackground(new java.awt.Color(248, 248, 248));
        pulsosTexto.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        pulsosTexto.setForeground(new java.awt.Color(51, 51, 51));
        pulsosTexto.setText("pulsos");

        comprarAClasess.setText("Aprender Clases");
        comprarAClasess.setToolTipText("Genera 1 pulso extra cada segundo.");
        comprarAClasess.setEnabled(false);
        comprarAClasess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprarAClasessActionPerformed(evt);
            }
        });

        costoAClases.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        costoAClases.setForeground(new java.awt.Color(102, 102, 102));
        costoAClases.setText("Costo: 100 pulsos");

        comprarARelaciones.setText("Aprender Relaciones");
        comprarARelaciones.setToolTipText("Genera 14 pulsos extras cada 2 segs.");
        comprarARelaciones.setEnabled(false);
        comprarARelaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprarARelacionesActionPerformed(evt);
            }
        });

        costoARelaciones.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        costoARelaciones.setForeground(new java.awt.Color(102, 102, 102));
        costoARelaciones.setText("Costo: 200 pulsos");

        comprarAHerencia.setText("Aprender Herencia");
        comprarAHerencia.setToolTipText("Genera 20 pulsos cada 2 segs.");
        comprarAHerencia.setEnabled(false);
        comprarAHerencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprarAHerenciaActionPerformed(evt);
            }
        });

        costoAHerencia.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        costoAHerencia.setForeground(new java.awt.Color(102, 102, 102));
        costoAHerencia.setText("Costo: 400 pulsos");

        comprarAColecciones.setText("Aprender Colecciones");
        comprarAColecciones.setToolTipText("Genera 12 pulsos extras cada segundo.");
        comprarAColecciones.setEnabled(false);
        comprarAColecciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprarAColeccionesActionPerformed(evt);
            }
        });

        costoAColecciones.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        costoAColecciones.setForeground(new java.awt.Color(102, 102, 102));
        costoAColecciones.setText("Costo: 600 pulsos");

        jLabel1.setText("Cheatcode:");

        cheatInput.setText("cheat");

        okCheat.setText("OK");
        okCheat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okCheatActionPerformed(evt);
            }
        });

        comprarEventosR.setText("Eventos Random");
        comprarEventosR.setToolTipText("Genera eventos aleatorios con buena o mala fortuna.");
        comprarEventosR.setEnabled(false);
        comprarEventosR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprarEventosRActionPerformed(evt);
            }
        });

        costoEventosR.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        costoEventosR.setForeground(new java.awt.Color(102, 102, 102));
        costoEventosR.setText("Costo: 50 pulsos");

        jLabel3.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Desbloqueables");

        prenderMic.setEnabled(false);
        prenderMic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prenderMicActionPerformed(evt);
            }
        });

        prenderCamara1.setEnabled(false);
        prenderCamara1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prenderCamara1ActionPerformed(evt);
            }
        });

        compartirPanta.setEnabled(false);
        compartirPanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compartirPantaActionPerformed(evt);
            }
        });

        costoMic.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        costoMic.setForeground(new java.awt.Color(102, 102, 102));
        costoMic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        costoMic.setText("1000");
        costoMic.setToolTipText("Costo");
        costoMic.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        costoCamara1.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        costoCamara1.setForeground(new java.awt.Color(102, 102, 102));
        costoCamara1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        costoCamara1.setText("1000");
        costoCamara1.setToolTipText("Costo");
        costoCamara1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        costoPantalla1.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        costoPantalla1.setForeground(new java.awt.Color(102, 102, 102));
        costoPantalla1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        costoPantalla1.setText("1000");
        costoPantalla1.setToolTipText("Costo");
        costoPantalla1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pLateralLayout = new javax.swing.GroupLayout(pLateral);
        pLateral.setLayout(pLateralLayout);
        pLateralLayout.setHorizontalGroup(
            pLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLateralLayout.createSequentialGroup()
                .addGroup(pLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pLateralLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(pLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pLateralLayout.createSequentialGroup()
                                .addGroup(pLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(costoAHerencia)
                                    .addComponent(comprarAHerencia, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(costoAClases, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comprarAClasess, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pLateralLayout.createSequentialGroup()
                                        .addGroup(pLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(prenderCamara1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(costoCamara1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(8, 8, 8)
                                        .addGroup(pLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pLateralLayout.createSequentialGroup()
                                                .addComponent(compartirPanta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(7, 7, 7)
                                                .addComponent(prenderMic, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(costoPantalla1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(7, 7, 7)
                        .addGroup(pLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(comprarARelaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(costoARelaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(costoAColecciones)
                            .addComponent(comprarAColecciones, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pLateralLayout.createSequentialGroup()
                        .addGroup(pLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pLateralLayout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cheatInput, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(okCheat, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pLateralLayout.createSequentialGroup()
                                .addGap(225, 225, 225)
                                .addComponent(pulsosTexto))
                            .addGroup(pLateralLayout.createSequentialGroup()
                                .addGap(193, 193, 193)
                                .addComponent(costoMic, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(90, 90, 90))
            .addGroup(pLateralLayout.createSequentialGroup()
                .addGroup(pLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pLateralLayout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(totalPulsos, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pLateralLayout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addGroup(pLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(comprarEventosR, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(costoEventosR))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pLateralLayout.setVerticalGroup(
            pLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLateralLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(totalPulsos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pulsosTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pLateralLayout.createSequentialGroup()
                        .addComponent(comprarAClasess, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(costoAClases))
                    .addGroup(pLateralLayout.createSequentialGroup()
                        .addComponent(comprarARelaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(costoARelaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(pLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pLateralLayout.createSequentialGroup()
                        .addGroup(pLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comprarAColecciones, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comprarAHerencia, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(costoAColecciones, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pLateralLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(costoAHerencia, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prenderMic, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(compartirPanta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prenderCamara1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(costoMic, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(costoCamara1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(costoPantalla1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addComponent(comprarEventosR, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(costoEventosR, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(247, 247, 247)
                .addGroup(pLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cheatInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(okCheat))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(pPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        pulsos++;

        totalPulsos.setText(Integer.toString(pulsos));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void progresoBarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_progresoBarStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_progresoBarStateChanged

    private void comprarEventosRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprarEventosRActionPerformed
        // TODO add your handling code here:
        if(eventooosRandom==false){
           comprarEventosR.setText(activado);
            eventooosRandom = true;
            pulsos-=50;
            Timer timef = new Timer(6500, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    int rand = (int) (Math.random() * 10);

                    if (rand > 2) {
                        eventosRPulsos.setForeground(Color.green);
                        switch (rand) {
                            case 3:
                            eventosRandomLabel.setText(eventosBien[rand]);
                            pulsos+=150;
                            eventosRPulsos.setText("+150");
                            break;
                            case 4:
                            eventosRandomLabel.setText(eventosBien[rand]);
                            pulsos+=50;
                            eventosRPulsos.setText("+50");
                            break;
                            case 5:
                            eventosRandomLabel.setText(eventosBien[rand]);
                            pulsos+=350;
                            eventosRPulsos.setText("+350");
                            break;
                            case 6:
                            eventosRandomLabel.setText(eventosBien[rand]);
                            pulsos+=10;
                            eventosRPulsos.setText("+10");
                            break;
                            case 7:
                            eventosRandomLabel.setText(eventosBien[rand]);
                            pulsos+=110;
                            eventosRPulsos.setText("+110");
                            break;
                            case 8:
                            eventosRandomLabel.setText(eventosBien[rand]);
                            pulsos+=210;
                            eventosRPulsos.setText("+210");
                            break;
                            case 9:
                            eventosRandomLabel.setText(eventosBien[rand]);
                            pulsos+=5;
                            eventosRPulsos.setText("+5");
                            break;
                            default:
                            throw new AssertionError();
                        }

                    } else {
                        eventosRandomLabel.setText(eventosMal[rand]);
                        pulsos-=270;
                        eventosRPulsos.setForeground(Color.red);
                        eventosRPulsos.setText("-270");
                    }

                }
            });
            timef.setRepeats(true);
            timef.setCoalesce(true);
            timef.start();
        }
    }//GEN-LAST:event_comprarEventosRActionPerformed

    private void okCheatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okCheatActionPerformed
        // TODO add your handling code here:
        String pwd= new String(cheatInput.getPassword());
        if(pwd.equalsIgnoreCase("AndresM")){
            pulsos=5000;
            System.out.println("Cheat activado");
            pPrincipal.setBackground(Color.DARK_GRAY);
        }
    }//GEN-LAST:event_okCheatActionPerformed

    private void comprarAColeccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprarAColeccionesActionPerformed
        // TODO add your handling code here:
        if(aprenderColecciones==false){
            comprarAColecciones.setText(activado);
            aprenderColecciones=true;
            pulsos-=600;
        }
    }//GEN-LAST:event_comprarAColeccionesActionPerformed

    private void comprarAHerenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprarAHerenciaActionPerformed
        // TODO add your handling code here:
        if (aprenderHerencia == false) {
            comprarAHerencia.setText(activado);
            aprenderHerencia = true;
            pulsos = pulsos - 400;
        }
    }//GEN-LAST:event_comprarAHerenciaActionPerformed

    private void comprarARelacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprarARelacionesActionPerformed
        // TODO add your handling code here:
        if (aprenderRelaciones == false) {
            comprarARelaciones.setText(activado);
            aprenderRelaciones = true;
            pulsos = pulsos - 200;
            Timer timee = new Timer(2000, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    pulsos += 14;

                    System.out.println("Esto es de AprenderRelaciones");
                    if (aprenderHerencia == true) {
                        pulsos += 20;
                        System.out.println("Esto es de AprenderHerencia");
                    }

                }
            });
            timee.setRepeats(true);
            timee.setCoalesce(true);
            timee.start();
        }
    }//GEN-LAST:event_comprarARelacionesActionPerformed

    private void comprarAClasessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprarAClasessActionPerformed
        // TODO add your handling code here:
        if (aprenderClases == false) {
            aprenderClases = true;
            comprarAClasess.setText(activado);
            pulsos = pulsos - 100;
            Timer timex = new Timer(1000, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    pulsos++;

                    totalPulsos.setText(Integer.toString(pulsos));
                    System.out.println("Esto es de AprenderClases");

                    if(aprenderColecciones=true){
                        pulsos+=12;
                        System.out.println("Esto es de AprenderColecciones");
                    }

                }
            });
            timex.setRepeats(true);
            timex.setCoalesce(true);
            timex.start();
        }
    }//GEN-LAST:event_comprarAClasessActionPerformed

    private void prenderMicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prenderMicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prenderMicActionPerformed

    private void prenderCamara1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prenderCamara1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prenderCamara1ActionPerformed

    private void compartirPantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compartirPantaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_compartirPantaActionPerformed

    /**
         * @param args the command line arguments
         */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField cheatInput;
    private javax.swing.JButton compartirPanta;
    private javax.swing.JButton comprarAClasess;
    private javax.swing.JButton comprarAColecciones;
    private javax.swing.JButton comprarAHerencia;
    private javax.swing.JButton comprarARelaciones;
    private javax.swing.JButton comprarEventosR;
    private javax.swing.JLabel costoAClases;
    private javax.swing.JLabel costoAColecciones;
    private javax.swing.JLabel costoAHerencia;
    private javax.swing.JLabel costoARelaciones;
    private javax.swing.JLabel costoCamara1;
    private javax.swing.JLabel costoEventosR;
    private javax.swing.JLabel costoMic;
    private javax.swing.JLabel costoPantalla1;
    private javax.swing.JLabel eventosRPulsos;
    private javax.swing.JLabel eventosRandomLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel numSalaLabel;
    private javax.swing.JButton okCheat;
    private javax.swing.JPanel pLateral;
    private javax.swing.JPanel pPrincipal;
    private javax.swing.JButton prenderCamara1;
    private javax.swing.JButton prenderMic;
    private javax.swing.JProgressBar progresoBar;
    private javax.swing.JLabel pulsosTexto;
    private javax.swing.JLabel salaLabel;
    private javax.swing.JLabel totalPulsos;
    // End of variables declaration//GEN-END:variables
}
